phoneme.exe: phoneme.obj english.obj parse.obj saynum.obj spellword.obj
	links phoneme english parse saynum spellword
phoneme.obj: phoneme.c
	lcs phoneme
english.obj: english.c
	lcs english
parse.obj: parse.c
	lcs parse
saynum.obj: saynum.c
	lcs saynum
spellword.obj: spellword.c
	lcs spellword
