* black on gold edition with extra vocabs/maybe

** TODO:

To add, check and remove also, check repeats:

62175 also as new vocab: check repeats: SPELLENA_62175.h

French: 2352 - re-check current file and additions...

creatures, animal, spanish, et*2=5

//TABLE bends, test all, check alphons position, change any order of vocabs

** older

//////////////////////// 93.35%

DONE///// checking spkspellone and two for faults: DONE but also doesn't match our new SPELL.h from apparently same roms

also 2303 and 2304 seems to repeat vocab and is not ENGLISH but seems better quality than speakspellone and two

but 2303 has zee in old version, and new extraction has zed ???? where is zee????

//DONEdupes from 2303 and 2304

// TODO; lose 2321,2322 DONE!

TODO: sort out ROMS clearly:

- duplicates in 2303/4 and tmc0351n2l.vsm/tmc0352n2l - does SPELLEN of both do the job with no duplicates?
- 2352 updates

new is SPELLEN and SPELLENA to fit in

///

- TODO: CHECK:fix french vocab in: 2352: vocab_2352.h - COMPARE - what we have is now additional french but remove some...

DONEcheck/fix also: tmc0351n2l.vsm and tmc0352n2l - in spkspellone / and two as these have glitches

/////

low on memory so what to do...????

- new vocabs to check and add, now all collected in: /root/projects/ERD_MODULES/WORM/revival/src/new_data
cleaned up now... to make as headers...

in progress: all new vocabs are ready

- table bend and where we put this!

///// notes

new vocabs HOWTO:

- dump and check duplicates...
- test in ti_lpc
- header in relevant xxxxx.h

catalogue them: vocaid, redo french, etf

/////

- where we put new vocabs!?

// use command: ./mame vocaid 2> test1E

eg. [[file:~/projects/ERD_MODULES/WORM/mame/vocaid.h::// VOCAID CD2357]]

- fix eg. french vocab, check others using ti_lpc

- using new commandline ti_lpc and shell - first of all we need to get addresses using eg:

: ./ti_lpc_cmd mode=romlist rom0=cd62190.vsm fnameout=zzzaddr_listIT.txt verb=on

zero the index list and then run ./over.sh to dump hex (edit that bash script to ref the right ROM!)

- extra vocabs: catalogue and extract these (up to full memory) 

vocaid: vocaid.h 

Now we have all extras for these!

snread: tntell:

snspell: italian, math etc see below

- new table bend mode to test - also add modes for other vocabs with bends of tables... other bends we already have...

- how do we extract from ROMS using mame (fine for vocaid and other overlay ones like tntell) ... but not for snspell, snread // how do we operate those?

//

linger is last word of first vocab bank:  vocab_2303

const uint8_t sp_spk2303nn101[]         __attribute__ ((section (".flash")))  ={0x2A, 0x30, 0x37, 0x25, 0x36, 0x36, 0x63, 0xC8, 0xA1, 0x58, 0x16, 0xD6, 0x25, 0xC6, 0x72, 0xB7, 0x5D, 0x77, 0x75, 0x84, 0x33, 0x56, 0x6C, 0x5E, 0xFB, 0x30, 0xEF, 0x24, 0x35, 0xA7, 0xD2, 0x61, 0xC9, 0xB3, 0x5B, 0x77, 0xE1, 0xC3, 0x92, 0x23, 0x8F, 0x49, 0x23, 0x87, 0x7B, 0x45, 0xD3, 0xAE, 0xB1, 0x97, 0x30, 0x92, 0xC7, 0xD2, 0xE3, 0xE, 0x65, 0x35, 0x5C, 0x85, 0xC9, 0xE9, 0xA6, 0xFB, 0x1E, 0x53, 0x92, 0x96, 0x37, 0xCC, 0x27, 0x97, 0x64, 0xAD, 0x63, 0x5A, 0x34, 0x6E, 0xC9, 0x26, 0x96, 0x8E, 0x6C, 0xB5, 0x92, 0xA9, 0x64, 0x13, 0xD1, 0x68, 0x65, 0x3B, 0x59, 0x37, 0x7C, 0xD1, 0x2E, 0xBB, 0x8E, 0x6E, 0x4A, 0x70, 0x7C, 0x6A, 0x9E, 0xA3, 0x4D, 0x1B, 0x8A, 0xEC, 0x5D, 0x4B, 0x5F, 0xF1, 0x3C, 0x85, 0xB, 0xE, 0xE, 0x51, 0xD9, 0x3F};


** where we can fit these vocab banks in - what is spare?

there are 67 banks in first modes...

- what modes use the full sets of banks?

those which make use of newsay and newsay_lowbit

- and how we could squeeze in more? across lowbits // assess lowbits mode...

- vocabs are of different lengths but we need to keep identity of vocabs

// tested extents - how many banks we can fit in? as we have some vocab banks with 131 phrases...

*YES! we can fit in extra banks - but FLASH is at 96%*

- how much does one ROM take...? 100 words is like 1% of rom so we can fit in say 200-300 words...

** table bends

- use exy[] array to access tables - we need to reset tables on entering the mode...

diff tables for 5100 and 5200

tables: energy, period, chirp, K1-K10 ... 

length of full table elements... where we reset (on entry?)

** mame patched so outputs codes

- it now outputs hex dump - try with unknown roms and ti_lpc

+but hex is dump of raw values - so not rom values and can't be tested in ti_lpc but in LPC we can play raw...+

eg. for 5110 from snread/2394:

0xb, 0xba, 0x94, 0xea, 0xa1, 0x8c, 0x36, 0xdc, 0x70, 0xc3, 0xd, 0x37, 0xda, 0x68, 0xa3, 0x8d, 0x36, 0xda, 0x78, 0xe3, 0x8d, 0x37, 0xde, 0x78, 0x93, 0x4d, 0x36, 0xd9, 0x64, 0x93, 0x4d, 0x37, 0xdd, 0x74, 0xd3, 0x4d, 0x37, 0xdc, 0x70, 0xc2, 0x8, 0x1f,

0xae, 0xf2, 0x78, 0xa5, 0x18, 0x5a, 0x63, 0xec, 0xfe, 0x58, 0xe7, 0xc3, 0x2b, 0xcc, 0xeb, 0xd5, 0x47, 0xb9, 0xa4, 0x5a, 0xaa, 0x8b, 0x97, 0x8, 0xb3, 0x29, 0x8c, 0x56, 0xd, 0x11, 0x96, 0x72, 0x89, 0x2e, 0x2e, 0x2a, 0x2c, 0xb0, 0x8a, 0xc8, 0x9d, 0x8c, 0xef, 0x1, 0xde, 0x92, 0x27, 0x3a, 0xef, 0x10, 0x38, 0x98, 0xd4, 0x2, 0xf, 0x86, 0xff, 0xc6, 0x54, 0x45, 0x7d, 0x1d, 0x9f, 0x53, 0x58, 0xe8, 0xc4, 0xb9, 0xe1, 0xa6, 0x9b, 0x6f, 0xbe, 0xe9, 0xc6, 0x1b, 0x58, 0x30, 0xa9, 0xac, 0x38, 0x4e, 0x3, 0x80, 0x1, 0xde, 0xbb, 0x72, 0x80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x98, 0xee, 0x58, 0x97, 0xa1, 0xb5, 0xc9, 0x37, 0xf7, 0x94, 0xa2, 0xca, 0x32, 0xb0, 0x27, 0x3b, 0x9d, 0x98, 0x5c, 0xa4, 0x7b, 0x3c, 0xbe, 0xf9, 0xe6, 0x9b, 0x77, 0x36, 0xcd, 0x9b, 0xac, 0x64, 0xb1, 0x5b, 0xf3, 0x8a, 0x56, 0xee, 0x34, 0x58, 0x9b, 0x1d, 0x5b, 0x50, 0xf6, 0xd7, 0xc1, 0x17, 0x15, 0x27, 0xfc, 0xa7, 0x60, 0x56, 0x8d, 0xda, 0x28, 0x4b, 0xbe, 0xc, 0xcc, 0x2e, 0x57,

0x26, 0x72, 0xb5, 0x67, 0x10, 0x4e, 0x6c, 0x88, 0xa1, 0x79, 0xcf, 0xfb, 0x95, 0x4d, 0xfe, 0x74, 0xdb, 0x2e, 0xe3, 0xed, 0x35, 0x6b, 0xa4, 0xdd, 0xe6, 0x98, 0xe4, 0xda, 0x55, 0xdb, 0xee, 0x75, 0x37, 0xec, 0x38, 0x93, 0x4b, 0xc5, 0x43, 0x66, 0x94, 0x52, 0x9f, 0x7d, 0x36, 0x39, 0x5a, 0x88, 0xf2, 0x52, 0x62, 0xb3, 0xce, 0x32, 0xeb, 0xac, 0xb3, 0x4a, 0x3d, 0xb4, 0x84, 0x9, 0xdd,   0x7

Press TAB to change machine config. remember F1 is also a key...

keys to access each box

** catalogue vocabs

*** know we used in roms:

USA rom0 file: tmc0351n2l.vsm USA rom1 file: tmc0352n2l.vsm:

from spkspell:
  -rw-r--r-- 1 root root  98584 Jul 27  2022 vocab_spkspellone.h : 
  -rw-r--r-- 1 root root 105576 Jul 27  2022 vocab_spkspelltwo.h

vocab_2303.h: UK?
vocab_2304.h:
vocab_2321.h: japan?
vocab_2322.h:
vocab_2350.h: ??
vocab_2352.h: french - can see some issues... could check all vocabs using ti_lpc! automate this somehow??? - changed code so prints hex ... UPDATE...

2352

*** unused roms we have

2352: french to redo...DONE: CD2352.txt

cd2319.vsm: spanish ok DONE SPA.txt
cd2320.vsm: ^^

cd2354a.vsm: more english - we dont have... compact speak and spell DONE COM.txt

cd2381.vsm: speak and math ??ok ????? MATH.txt

cd2392.vsm: speak and math // some...
cd2393.vsm:

cd2394a.vsm: speak and read // no joy - see above from mame // letters are there
cd2395a.vsm

cd2614.vsm (4096 bytes?) math? non

//cd62190.vsm: italian - some decoding in ti_lpc

what other roms we can get/try?

// now we have some of these in new_roms...

speak and spell:

magmods           Magnificent Modifiers
migverbs          Mighty Verbs
Xmagasrue          Les Magasins de la Rue (Module No. 4)
basbuild          Basic Builders
Xetf               E.T. Fantasy
homohero          Homonym Heroes
nounends          Noun Endings
sstump46          Super Stumpers 4-6
sstump78          Super Stumpers 7-8
vpower            Vowel Power
vventure          Vowel Ventures
motsbase          Les Mots de Base (Module No. 1)
motsdiff          Les Mots Difficiles (Module No. 2)

snread: NON!

dogonlog          A Dog on a Log
ghouse            A Ghost in the House
ontrack           On the Track
seasight          Sea Sights
mknight           The Millionth Knight
sealfly           The Seal That Could Fly
3circle           The Third Circle
whoszoo           Who's Who at the Zoo

tntell: 

Xet                E.T. the Extra-Terrestial
Nalphabet          Alphabet Fun
Xanimalfr          Animal Friends
Nnumfun            Number Fun
Naboutme           All About Me
Xwot               World of Transportation
Xlilcreat          Little Creatures

lanteach - german tutor

vocaid: vocaid.zip: 2357 - non in tl_lpc and in mame YES: overlay codes: 1E-telephone, 1D-alphanumeric, 1C-leisure, 1B-bedside overlay

** ti_lpc

- saved text is what. how to output full list...

** how we access these and know if we don't include them

- using own tools like lpcread and lpcsay (re-acquaint - wierd values in lpcread but should be fine)

what was one we use to guess outs?

lpc_split and now:

: ./lpc_spliter ../../../../../../Downloads/speaky_2023/cd2394a.vsm 0 > testsplit                                                                                                                       ~/projects/ERD_MODULES/WORM/revival/src/LPC

and can load it in ti_lpc

- using ti_lpc which seems to guess locations well eg. for speak/math cd2392.vsm 

- search in own vocabs for hex strings

** other options

- bends of tables such as chirp for vocabs...

** what we work towards in raven from WORM/TMS5xxx and others...?

- live TMS encoding and decode/playback

** is this the correct codebase or move to revival MOVED TO REVIVAL !

** programming header again...

WORM: 3.3v/SWCK/GND/SWDIO (SWDIO on left from back)

PROGRAMMER: VDD, SWCLK, GND, SWDIO (so no swop)

** new TMS encodings of speech - pywizard?

** check code against ti_lpc which seems cleaner sounding

- check all co-effs
- check process as seems quite different // re-code?
