* new progress

** 2/1/2017

- working on ROMS, TODO: extract rest of echo II female voices, rest
  of speak and spell, where is TRON=sp0256 (work on those when we get
  to that)

-lpc_split adapted for: ./lpc_split D034 0 > roms/vocab_D034.h

- LPC/roms - all the 2xxx ones to fix up and test, alongside D0->34

** 3/1

5100 to check/trim all:

vocab_2321.h-DONE
vocab_2322.h-DONE
vocab_2352.h-DONE
vocab_2350.h-DONE
vocab_2303.h-DONE
vocab_2304.h-DONE

5200 all d000-d034 - DONE but need to check against echo_female (all
there are in D000 and D003) 

- also groupings of these vocabs TODO - for example numbers, letters, allophones etc... so that banks make sense

/////

- new MAME votrax to PORT: started but filter issue...cur_va DONE -
  seems to work but timing is not so solid and we need vocab data

- TODO - general below, ADC extent (eg. for modes, vocab) and vocabulary, how much
  better does mame code sound for say echo II speech/5200 Dxxx samples

- tested speak and spell on mame code sounds fine, some end glitch???

- extent good till 128 at least

- inverted ADC, do Y and speed swop - DONE!

*- how we can bend TMS - other excitation-TRY with inverse filter in, X/Y/Z bendings, trigger=freeze?*

** 4/1+

- proof of concept votrax working -. new mode... TODO: ARM port, vocabs, TTS- see also deladriere code

// wow.c, gorf.c (where else? gottlieb) - convert to arrays and check against roms for each

, bends

- any changes for others in MAME? CHECK!

- grouping of TMS vocabs and clear chipsets marked for arm mam code

- bends of TMS

- inversion of any ADC?

* general TODO

- test new x220 flash and run! cableDONE

- start with one mode and its extensions and define/clean below from there

- basics eg. ROMS, filenamings, compost, 

XYZSPEED arrangement

, ADC extent,-128 at least

  control models:

eg. - TMS could be CV controlled with trigger/freeze=toggle settings - model for this kind of control

, layout, interpolXNO!, split of glottal sources, new code,
  TTS and where it is relevant, what else?

- basic modes templated: XYZ, speed, triggering, compost

each source/filter mode has regular in (eg. TMS, external in, other glottal sources)
X,Y,Z and speed...

- LPC inverse filter as excitation and/or NOT so...
- vocoder and experimental modes
- *worm control - MOVE OUT TO NEW MODULE alongside RAVEN!*
- clean ups, documentation, tests and release

* TMS ROMS

classify each ROM in tms dir

** 5100-speak and spell

** 5200- early echo II, disks of TRON, TI99/4 

** 5220- later echo II, BBC MICRO

* notes from README.org

- source/filter model we have sources as: input straight (fine for
oscillation or noise in), inverse filtered in, inv in as triggered
wavetable, inverse filtered audio buffer, audio buffer (and toggle off
write on use of audio buffer), physical glottal model, stored
wavetable as in raven, generators eg. pulse, square, and original
(eg. TMS, Klatt)


* main modes overview - otherwise see modes.org

** basic modes to do with suggested extensions

1. TMS
2. SP0256
3. digitalker
4. votrax
5. SAM
6. klatt/nvp variations
7. LPC vocoder
8. vocoder
9. vosim/fof etc.
10. compost
11. tube/glottal/wavetable
12. voicform?

* chipsets/emulation/roms

rom data structure - only makes sense for TMS

- array pointer of pointers
- number of entries/length 
- chip ident (enum)

*** 5100//522x

in LPC/roms:
vocab_spkspell.h - 5100 all
vocab_acorn.h -
vocab_custom.h -
vocab_large_male.h -
vocab_male.h -
vocab_talko.h - checl against others
vocab_testroms.h - inc allophones...
vocab_ti99.h -

and more...

*** sp0256

256_roms.h - 

m_rom_256_012 - ?

m_rom_256_al2 - 64 allophones

*** digitalker

digitalker_roms.h - 

m_rom (rename!)

* questions:

** all roms/dumps

MPF - TMS- http://electrickery.xs4all.nl/comp/mpf1/doc/index.html where are extended speech roms?

** control

** glottal sources

** vocoding

** data sources/wavetables to generate
