* MAJOR MODES 

1-SELX
2-SELY
3-SELZ
4-SPEED

- run down by name, files, description, manual desc, 1-SELX/2-Y/3-Z/4-SPEED/AND_TRIGGER, notes, TODO

** 0) TMS5220



** 1) FULLKLATT: rsyth-2.0-port, main.c

SELX- chooses which position - like X axis
SELY- chooses phoneme for that position - like Y axis
SELZ- length of phoneme at that position

*** notes

- added TRIANGULAR source from parwv.c to test-> DONE, also other changes from parwv to finish
- glitchy to fix with lots of clicks -?

-- could be glitch in updatingMAYBE, bad codeSANITY CHECK, speedNO,
-- msec per frameNO, glottal sourceNO, volumeNO, just that doesn't fit phraseMOST LIKELYbut how to fix - or try add after filter (works but dullness)
-- what we need is test phrase from klatt out (where is our lap test code = docs/rsynth-2-un)

- that in main.c we have the SELX etc selections
- that there was a pitchbend but now where we can have it if not in another mode (pitch can be speed)

*** TODO:

- how we change flutter and TLTdb(where) and Kskew?-> see in def_pars.c - what are settings for say female or different voices/vocal fry?

fill in here:

- test substitution of wavetable etc and other excitations in - but is x4 oversampled?

[ simple wavetable with SPEED as freq ]

- SPEED setting to do (and maybe test interpol there)

** X) WAVETABLE:

- choose wavetableX, frequencySPEED and Y/Z as tube//other filters

- trigger as resync start of wavetable

- oversampling or not? TEST - doesn't work with oversample - fixed - any difference?

*** TODO

- as above, 2d wavetable

- new wavetables from wavs, and new generated:

we need to derive and edit wavetables first: real raven, real human,
historical speech synth models, glottal models as below with varying parameters...

more plague wavetables using different code - catalogue wavetables...

LF, raven etc...
