* notes specific to raven and worm voices

** README.org notes

** paper notes

- tube model is not so important

** references/links

*** Fletcher (1988): Bird Song .... Corvus mellori... raven

200Hz fundamental syrinx, 70mm trachea

Formants are 1.4/2/3/3.7 and 5 KHz - see also animals.scm below

** PLAN

approaches are: 

- papers and glottal models towards crow voice - tubes are not so important as modelling source. what are models?

2 mass model? Ishizaka and Flanagan: IF_C = hellostkx and IF_final.m 

model in Fletcher? and in Smyth and Smith: Bernoulli and waveguide

is  /root/sc3-plugins/source/MembraneUGens/sc useful here? or spring class? // pmsc/pmpd - physical modelling // flauta...

- LPC/ UNIANAL

- fake it. trautonium. noise, vibrato and envelopes - see CLM:
  bird.clm, bigbird.ins (to test), bird.scm, animals.scm - also
  muffwiggler thread and notes from that - //summarise//

- plague modelling as glottal model: DarkInt and Blackdeath code bases/simulation

/root/collected/blackdeath/code/simulations

[[file:~/dark-interpreter/darkintv2may2015/simulation.c]]

** 9/3/2016

snd: to work with we use save as - wave header and ubyte

and from animals.scm we have

;;; American crow

(define (nrcos->polywave n r scl)
  (if (and (positive? n)
	   (< n 8192))
      (let ((lst ())
	    (total (polynomial (make-float-vector n 1.0) r)))
	(set! scl (/ scl total))
	(do ((i 0 (+ i 1)))
	    ((= i n) (reverse lst))
	  (set! lst (cons (* scl (expt r i)) (cons (+ i 1) lst)))))
      (error 'out-of-range "nrcos->polywave: too many partials")))

(defanimal (american-crow beg amp)
  (let ((dur 0.27))
    (let ((start (seconds->samples beg))
	  (stop (seconds->samples (+ beg dur)))
	  (ampf (make-env '(0.000 0.000 .02 .1  .04 .01 .06 0.056 0.110 0.700 0.258 1.000  0.344 0.970  0.369 0.677 .7 .3  1.000 0.000)
			  :duration dur :scaler (* 2 amp)))
	  (frqf (make-env '(0.000 0.360 0.038 0.362 0.052 0.396 0.076 0.403 0.095 0.445 0.129 0.445 0.153 0.493 
				  0.201 0.495 0.231 0.501 0.260 0.490 0.297 0.503 0.317 0.499 0.346 0.473 0.407 0.473 
				  0.435 0.424 0.495 0.439 0.528 0.392 0.589 0.405 0.621 0.362 0.677 0.373 0.704 0.332 
				  0.767 0.325 0.791 0.281 0.832 0.278 0.859 0.251 0.890 0.225 0.912 0.255 0.950 0.263 1.000 0.26)
			  :duration dur :scaler (hz->radians 1250.0)))
	  (frm1 (make-formant 1400 .995))
	  (frm2 (make-formant 5500 .98))
	  (frm3 (make-formant 3800 .98))
	  
	  (fr1 (* 2 20 (sin (hz->radians 1400))))
	  (fr2 (* 2 (sin (hz->radians 5500))))
	  (fr3 (* 2 2 (sin (hz->radians 3800))))
	  
	  (gen (make-polywave 0.0 (nrcos->polywave 15 .75 1.0)))
	  (rnd (make-rand-interp 5000 .007)))

      (let ((fb (vector frm1 frm2 frm3))
	    (fs (float-vector fr1 fr2 fr3)))
	(set! fb (make-formant-bank fb fs))

	(do ((i start (+ i 1)))
	    ((= i stop))
	  (outa i (formant-bank fb (* (env ampf)
				      (polywave gen (+ (env frqf)
						       (rand-interp rnd)))))))))))

;; (with-sound (:play #t) (american-crow 0 .5))

** 10/3 DOUBLE ISSUE! how do we solve - with new gcc-arm?

- we need to concentrate on working implementations of one and two mass models (refs: Fletcher, Rodet, Ishizaka and Flanagan)

implemented in praat (as part of artic. model), balloon1.cpp=IF_final.m which is documented in 614_final_report.pdf, any-where else?

- that worms can also be modelled as masses moving in a tract?

praat where: see praat/speaker -> artsynth (but how much we can modify?)

[[file:~/projects/ERD_modules/worm/docs/praat/artsynth/Artword_Speaker_to_Sound.cpp::autoSound%20Artword_Speaker_to_Sound%20(Artword%20artword,%20Speaker%20speaker,][file:~/projects/ERD_modules/worm/docs/praat/artsynth/Artword_Speaker_to_Sound.cpp::autoSound Artword_Speaker_to_Sound (Artword artword, Speaker speaker,]]

*** notes

IF_final.m plots fine... testing now with wavwrite in octave: wavwrite(out, 32000, "test.wav"); but NO LUCK!!

balloon1.cpp ported to balloon. stkfloat is double!!! produces something but faint and need to amp it by 1000.0 GAIN?

TODO: examine parameters - see what we can fit here from Fletcher and co! see kahrs.pdf but is all quite vague

/// also we need to vary sub-glottal pressure regularly as in: Synthesis_of_voiced_sounds_using_low-dim.pdf - TESTING

/// play -t raw --bits 16 --channels 1 --encoding unsigned-integer --rate 32000 testball.pcm repeat 9999

so far parameters we have make no sound or just onset click - try in
matlab/octave - same result of just one start impulse even if vary k/spring constant!

- doubles also in praat /// and with make doesn't compile.. q if to abstract out

** 11/3 ignore double issues and just explore code and simulations

- concentrate on balloon.c - running through parameters to see what
  makes sense - increasing k/springiness seems to work, should damping be independent or?

see http://www.dei.unipd.it/~avanzini/downloads/paper/avanzini_eurosp01_revised.pdf for human parameters

- K spring constant (and mass for clickiness) is important for frequency but can't seem now to
  raise higher (unless leave out reset old values)

Ag01 can't seem vary at all without silence, S doesn;t do much,,,, try vary d1 glottal width/thickness which makes it more bitty/screechy

note SQ (speed quotient in avanzini) in relation to vocal fry - also more studies on vocal fry towards raven voice

- try coupling tube to this model???? in fletcher etc. how was this
  done? model acoustic waves in trachea // reflected wave from open
  beak ... length of trachea is 70mm, diameter is 7mm

*** pdf summary/lists

**** 2003 Elemans etal AnimBiol.pdf - overview

- reed model is possible. what do we have as tests?

- describes Fletcher well and links of other models to Ish/two mass: eg. Gardner, Fry, Laje and Mindlin, Laje

- American crow also in Goller and Larsen 1997

- mentions Brittan-Powell (1997) physical model -> this is JAS00578.pdf

**** p0244-p0252.pdf

- syringeal anatomy in crow

**** Synthasaurus.pdf

- basic animal sounds using Perry Cook-like model

- look at how glottal excitation is produced

**** 2006 Zaccarelli etal ActaAcustica.pdf

*** misc

[[file:~/projects/ERD_modules/worm/docs/flauta/orig/modules/Excitation.cpp]] - note also bernoulli there

[[file:~/sc3-plugins/source/StkUGens/stk-4.4.2/src/Flute.cpp::\brief%20STK%20flute%20physical%20model%20class.][file:~/sc3-plugins/source/StkUGens/stk-4.4.2/src/Flute.cpp::\brief STK flute physical model class.]]


from flowgen_shimmer ... how raven approximates to closed quotient, speed etc. (vocal fry?) - re-check lfgen

  printf(" Simulated airflow based on Fant (1979),\n");
  printf(" Glottal Source and Excitation Analysis,\n");
  printf(" STL-QPSR 1/1979, pp. 85-107\n\n");
  printf("usage:\n");
  printf("%s -o file [-args {description (defaults <range>)}]\n\n",
							   "voicegen");
  printf("-o x {Output file (.wav, pcm, 16 bits/sample)}\n");
  printf("-r x {sampling Rate (22050 Hz <44100, 22050, or 11025>)}\n");
  printf("-d x {Duration (> 0.5 seconds)}\n");
  printf("-j x {jitter (0% <0-10%>)}\n");
  printf("-c x {closed quotient (.55 <0-1>)}\n");
  printf("-f x {Fundamental frequency, F0, 120 Hz }\n");
  printf("-g x {Glottal formant, Fg > F0, in Fant's (1979) model, 125 Hz }\n");
  printf("-k x {Speed of closure, K, in Fant's (1979) model 0.65 <0.55-1.00>}\n");
  printf("-z x {Variation of speed of closure (0.0 <0-1.0>))}\n");
  printf("-s x {shimmer (0.0 <0-10%>))}\n");
  printf("-n x {cycle-to-cycle SNR (0 dB  <0-50>) \n");
  printf("      aditive noise, uniforme distribution, closed phase}\n");
  printf("-a x {maximum amplitude (12000 <0-32767>)}\n");
  printf("-l x {DC flow, proportion of max amplitude (0.0 <0-0.30>))}\n");

*** TODO

- reed model is possible. what do we have? reedtable in stk (clarinet/blowhole - how does it work?), SC- spring, membrane?

- port twotube to become one tube in raven.c // or keep as two tubes?

- review models. what we don't have: one mass model, fletcher 1988 model, gardner, fry (exact refs)

- look at new refs. also Herzel/Titze

- FOF and other approach

- elements BLOW to investigate: [[file:~/projects/ERD_modules/older/eurorack/elements/dsp/tube.cc::/%20Simple%20waveguide%20tube.][file:~/projects/ERD_modules/older/eurorack/elements/dsp/tube.cc::/ Simple waveguide tube.]] and exciter is quite simple? - granular/wave???

- http://www.dei.unipd.it/~avanzini/phdthesis/th_download.html has mass models and reed thing!

- CDROM Perry Cook code and book!

** 12/3

raven.c compiles with tube code - to test - tube doesn't seem make
much difference... (reverted now to 2 tube code just to check... and can hear some differences but need test with better source)

is tube code inc reflection of open end tube as in JOS article?

- also maybe is good to coax IF model parameters here towards crow/200 Hz fundamental?

- re-test tube code with simple square wave oscillator - code simply all excitations so they can easily be ported to WORM!

- try SC examples: stringy, modify sources???

(
{
var delay1, delay2, source; 

//k from -1 to 1

//in samples
delay1= 100; 
delay2= 40;

source= WhiteNoise.ar(0.5)*EnvGen.ar(Env([1,1,0],[(delay1+delay2)/SampleRate.ir,0.0]), Impulse.kr(MouseY.kr(1,4)));

TwoTube.ar(source,MouseX.kr(-1,1),0.99,delay1,delay2); 
}.play

)

////SC notes:

http://swiki.hfbk-hamburg.de/MusicTechnology/848.diff?id=30

M-x sclang-start
M-x sclang-server-boot
C-x C-e eval
C-c C-s STOP!

** 13/3

- where we are with all glottal sources before start on tube/waveguide models

*** clear functions - follow SC model

void TwoTube_Ctor(TwoTube* unit) { -> init, allocs memory

void TwoTube_next(TwoTube *unit, int inNumSamples) {

IN and OUT pointers we can put in next, how we work with function pointers for each generate/next is question

*** LIST GLOTTAL SOURCES and progress so far

Liljencraants/Fant: lfgen.c

Rosenberg in lfgen.c

IF model - two mass model Ishizaka: raven.c

plague oscillation (where and how is reset?):

**** others:

[[file:~/projects/ERD_modules/older/eurorack/elements/dsp/exciter.cc::/%20Exciter.][file:~/projects/ERD_modules/older/eurorack/elements/dsp/exciter.cc::/ Exciter.]]

tube.c has glottal wavetable calculations

wavetable from raven voice - how does it work with interpolation? examples?

square, noise, vibrato, pulse train (in STK VoicForm.h is looping sample/vibrato)

flowgen_shimmer: Fant airflow

FOF (not strictly excitation) -> see Cook: 

all animal refs above

what is excitation in praat?

- http://www.dei.unipd.it/~avanzini/phdthesis/th_download.html has mass models and reed thing!

- CDROM Perry Cook code and book - also for tubes and FOF

[[file:~/projects/ERD_modules/worm/docs/flauta/orig/modules/Excitation.cpp]] - note also bernoulli there

[[file:~/sc3-plugins/source/StkUGens/stk-4.4.2/src/Flute.cpp::\brief%20STK%20flute%20physical%20model%20class.][file:~/sc3-plugins/source/StkUGens/stk-4.4.2/src/Flute.cpp::\brief STK flute physical model class.]]

SPASM two glottal oscillators: file:~/projects/ERD_modules/worm/docs/singer.scm::;;; Perry Cook's physical model of the vocal tract as described in:]] 

- http://homepage.univie.ac.at/christian.herbst//python/glottal_air_flow_models_8py_source.html = KLGLOTT88 and Rosenberg

now as *glottalair.py* and writing wav file - seems working -> port to C (also Rosenberg tests in lfgen.c are working)

**** Klatt/klsyn/nvp

klatt/klsyn - extractions from these and which exact code to use - nvp?

in nvp there is no skew but is in klsyn:

klsyn: The variable 'sk', "skew to alternate periods", is the number
        of 25 microsecond increments to be added to and subtracted
        from successive fundamental period durations in order to
        simulate one aspect of vocal fry, the tendency for alternate
        periods to be more similar in duration than adjacent periods.


**** LPC inverse filter:

This is accomplished by inverse-filtering the signal with the LPC, raising the parts of the spectrum which the LPC says are low, and lowering the parts which the LPC says are high. The end result, ideally, will be the source signal as if the person had no vocal tract at all.

http://doc.sccode.org/Classes/LPCAnalyzer.html

but inverse filter?

https://github.com/freedv/codec2/blob/master/src/lpc.c

[[file:~/projects/ERD_modules/worm/lpc.c::FILE........:%20lpc.c][file:~/projects/ERD_modules/worm/lpc.c::FILE........: lpc.c]]


**** Blip from SC from APEX/voiceosurces.sc

ApexSource01 {
	*ar { arg fo=100, invQ=0.1, scale=1.4, mul=1;
		var flow;
		flow = RLPF.ar(Blip.ar(fo, mul: 10000), scale*fo, invQ, invQ/fo);
		^HPZ1.ar(flow, mul);   // +6 dB/octave
	}
}


*** TUBE/waveguide models and notes

- tube.c from gnuspeech

- twotube and ntube from SC

- praat

- LFgen waveguide

file:~/projects/ERD_modules/worm/docs/singer.scm::;;; Perry Cook's physical model of the vocal tract as described in:]] 

Klatt formants

fixed vocoder style channels - what was ref?

4-dynklank resonators - save coeffs as table first

regular BPF etc. vowel in flowgen_shimmer


